/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingres_LocalIIapi */

#ifndef _Included_com_ingres_LocalIIapi
#define _Included_com_ingres_LocalIIapi
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: connectionInfo */
#undef com_ingres_LocalIIapi_DB_GLOBAL
#define com_ingres_LocalIIapi_DB_GLOBAL 1L
#undef com_ingres_LocalIIapi_DB_ACCESS
#define com_ingres_LocalIIapi_DB_ACCESS 2048L
#undef com_ingres_LocalIIapi_U_CREATEDB
#define com_ingres_LocalIIapi_U_CREATEDB 1L
#undef com_ingres_LocalIIapi_U_SECURITY
#define com_ingres_LocalIIapi_U_SECURITY 32768L
/* Inaccessible static: secureRandom */
/* Inaccessible static: processRegistry */
/* Inaccessible static: safeCommandLinePattern */
/* Inaccessible static: safeConnectIdPattern */
/*
 * Class:     com_ingres_LocalIIapi
 * Method:    InitAPI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_InitAPI
  (JNIEnv *, jclass);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getToolsAPIInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ingres_LocalIIapi_getToolsAPIInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    bootstrapCharsetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_bootstrapCharsetName
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeUnloadInstallation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativeUnloadInstallation
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    autoCommitOn
 * Signature: (Lcom/ingres/ConnectionHandle;)Lcom/ingres/TransactionHandle;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_autoCommitOn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    autoCommitOff
 * Signature: (Lcom/ingres/TransactionHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_autoCommitOff
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    commit
 * Signature: (Lcom/ingres/TransactionHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_commit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    rollback
 * Signature: (Lcom/ingres/TransactionHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_rollback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    connect
 * Signature: (ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/ingres/ConnectOptions;)Lcom/ingres/ConnectionHandle;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_connect
  (JNIEnv *, jobject, jboolean, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeDisconnect
 * Signature: (Lcom/ingres/ConnectionHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativeDisconnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeAbort
 * Signature: (Lcom/ingres/ConnectionHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativeAbort
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeQuery
 * Signature: (Lcom/ingres/ConnectionHandle;Lcom/ingres/TransactionHandle;Ljava/lang/String;Z)Lcom/ingres/StatementHandle;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_nativeQuery
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    executeProcedure
 * Signature: (Lcom/ingres/ConnectionHandle;Lcom/ingres/TransactionHandle;[Lcom/ingres/IIapi$Descriptor;[Lcom/ingres/IIapi$DataValue;)Lcom/ingres/StatementHandle;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_executeProcedure
  (JNIEnv *, jobject, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    putParameters
 * Signature: (Lcom/ingres/StatementHandle;[Lcom/ingres/IIapi$Descriptor;[Lcom/ingres/IIapi$DataValue;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_putParameters
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    cancel
 * Signature: (Lcom/ingres/StatementHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_cancel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    close
 * Signature: (Lcom/ingres/StatementHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getDescriptors
 * Signature: (Lcom/ingres/StatementHandle;)[Lcom/ingres/IIapi$Descriptor;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ingres_LocalIIapi_getDescriptors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getRows
 * Signature: (Lcom/ingres/StatementHandle;[Lcom/ingres/IIapi$Descriptor;[[Lcom/ingres/IIapi$DataValue;)I
 */
JNIEXPORT jint JNICALL Java_com_ingres_LocalIIapi_getRows
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getQueryInfo
 * Signature: (Lcom/ingres/StatementHandle;)Lcom/ingres/IIapi$QueryInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_getQueryInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_getEnv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    NMsymbols
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_NMsymbols
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeIDname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_nativeIDname
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    IDname_service
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_IDname_1service
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getVersionInfo
 * Signature: ()Lcom/ingres/IIapi$VersionInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_getVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_getVersionString
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getAPIVersionInfo
 * Signature: ()Lcom/ingres/IIapi$VersionInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_getAPIVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getAPIVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_getAPIVersionString
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    getSysInfo
 * Signature: ()Lcom/ingres/IIapi$SysInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_getSysInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    elevationRequired
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_elevationRequired
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    elevationRequiredWarning
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_elevationRequiredWarning
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    isElevationRequired
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ingres_LocalIIapi_isElevationRequired
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    checkPrivilege
 * Signature: (Ljava/lang/String;Lcom/ingres/IIapi$Privileges;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ingres_LocalIIapi_checkPrivilege
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    GCusrpwd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_GCusrpwd
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    GChostname
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_GChostname
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    GCtcpIpPort
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ingres_LocalIIapi_GCtcpIpPort
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    CMgetCharsetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_CMgetCharsetName
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    CMgetStdCharsetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_CMgetStdCharsetName
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMinit
 * Signature: ()Lcom/ingres/ContextHandle;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_PMinit
  (JNIEnv *, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMexpToRegExp
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_PMexpToRegExp
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMfree
 * Signature: (Lcom/ingres/ContextHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_PMfree
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMget
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_PMget
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMgetDefault
 * Signature: (Lcom/ingres/ContextHandle;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_PMgetDefault
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMhost
 * Signature: (Lcom/ingres/ContextHandle;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ingres_LocalIIapi_PMhost
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMload
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_PMload
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMnumElem
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ingres_LocalIIapi_PMnumElem
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMrestrict
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_PMrestrict
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMscan
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ingres_LocalIIapi_PMscan
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMsetDefault
 * Signature: (Lcom/ingres/ContextHandle;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_PMsetDefault
  (JNIEnv *, jobject, jobject, jint, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    PMlowerOn
 * Signature: (Lcom/ingres/ContextHandle;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_PMlowerOn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativePMinsert
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativePMinsert
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativePMdelete
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativePMdelete
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativePMwrite
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativePMwrite
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    nativeCRsetPMval
 * Signature: (Lcom/ingres/ContextHandle;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ingres_LocalIIapi_nativeCRsetPMval
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_ingres_LocalIIapi
 * Method:    LGgetLogPaths
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ingres_LocalIIapi_LGgetLogPaths
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
